on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run the action
        id: hello
        uses: ./.github/actions
        with:
          myInput: 'Chad'

      # Runs a set of commands using the runners shell
      - name: tell a joke
        run: |
          echo "here's a joke ${{ steps.hello.outputs.memory }}"
