on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run the action
        id: hello
        uses: ./
        with:
          myInput: 'Chad'

      # Runs a set of commands using the runners shell
      - name: output the memory
        run: |
          echo "${{ steps.hello.outputs.memory }}"
          echo $MY_NAME
