on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run the action
        id: hello
        uses: ./.github/actions
        with:
          myInput: 'Chad'
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      # Runs a set of commands using the runners shell
      - name: tell a joke
        run: |
          echo "${{ steps.hello.outputs.memory }}"
          curl -H "Accept: text/plain" https://icanhazdadjoke.com/
